name: xrft
dependencies:
  - python=3.6
  - pandas
  - xarray
  - dask
  - scipy
  - numpy
  - pytest
  - numpydoc
  - sphinx
  - ipython
  - matplotlib
  - pip:
    - docrep
    - nbsphinx
    - sphinx_rtd_theme
