name: test_env_xrft
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - xarray
  - dask
  - numpy
  - numpy_groupies
  - pytest
  - pip
  - black
  - cftime
  - pip:
    - codecov
    - pytest-cov
    - pytest-xdist
